const fs = require('fs')
const path = require('path')

enum OriginType {
  UNIVERSITY = 1,
  G_LEAGUE = 2,
  COUNTRY = 3,
}

enum Conference {
  Eastern = 0,
  Western = 1,
}

enum Division {
  Atlantic = 0,
  Central = 1,
  Southeast = 2,
  Northwest = 3,
  Pacific = 4,
  Southwest = 5,
}

enum Difficulty {
  EASY = 1,
  MEDIUM = 2,
  HARD = 3,
}

const NCAA_DIV_1_SCHOOLS = [
  'Abilene Christian University',
  'Adelphi University',
  'Adrian College',
  'Alabama Agricultural and Mechanical University',
  'Alabama State University',
  'Alcorn State University',
  'Alma College',
  'American International College',
  'American University',
  'Appalachian State University',
  'Arizona State University (ASU)',
  'Arkansas State University',
  'Armstrong State University',
  'Assumption University',
  'Auburn University',
  'Augusta University',
  'Augustana College',
  'Augustana University',
  'Aurora University',
  'Austin College',
  'Austin Peay State University',
  'Azusa Pacific University',
  'Babson College',
  'Ball State University',
  'Barton College',
  'Bates College',
  'Baylor University',
  'Bellarmine University',
  'Belmont Abbey College',
  'Belmont University',
  'Bemidji State University',
  'Benedict College',
  'Bentley University',
  'Bethune–Cookman University',
  'Biola University',
  'Birmingham-Southern College',
  'Bloomfield College',
  'Bloomsburg University of Pennsylvania',
  'Boise State University',
  'Boston College',
  'Boston University',
  'Bowdoin College',
  'Bowie State University',
  'Bowling Green State University',
  'Bradley University',
  'Brandeis University',
  'Brigham Young University (BYU)',
  'Brooklyn College',
  'Brown University',
  'Bryant University',
  'Bucknell University',
  'Butler University',
  'Caldwell University',
  'California Baptist University',
  'California Institute of Technology',
  'California Lutheran University',
  'California Polytechnic State University',
  'California State University, Bakersfield',
  'California State University, East Bay',
  'California State University, Fresno (Fresno State)',
  'California State University, Fullerton',
  'California State University, Long Beach',
  'California State University, Los Angeles (UCLA)',
  'California State University, Monterey Bay',
  'California State University, Northridge',
  'California State University, Sacramento',
  'Campbell University',
  'Canisius University',
  'Carson–Newman University',
  'Carthage College',
  'Catawba College',
  'Catholic University of America',
  'Centenary College of Louisiana',
  'Central Connecticut State University',
  'Central Michigan University',
  'Central State University',
  'Chapman University',
  'Charleston Southern University',
  'Chestnut Hill College',
  'Chicago State University',
  'Chowan University',
  'City College of the City University of New York',
  'Claremont McKenna College',
  'Clarkson University',
  'Clemson University',
  'Cleveland State University',
  'Coastal Carolina University',
  'Coker University',
  'Colby College',
  'Colby–Sawyer College',
  'Colgate University',
  'College of Charleston',
  'College of the Holy Cross',
  'Colorado College',
  'Colorado Mesa University',
  'Colorado State University',
  'Columbia University in the City of New York',
  'Concordia University Irvine',
  'Connecticut College',
  'Coppin State University',
  'Cornell University',
  'Creighton University',
  'Daemen University',
  'Dallas Baptist University',
  'Dartmouth College',
  'Davidson College',
  'Delaware State University',
  'Delaware Valley University',
  'DePaul University',
  'Drake University',
  'Drew University',
  'Drexel University',
  'Drury University',
  'Duke University',
  'Duquesne University of the Holy Spirit',
  'East Carolina University',
  'East Tennessee State University',
  'Eastern Illinois University',
  'Eastern Kentucky University',
  'Eastern Michigan University',
  'Eastern Washington University',
  'Eckerd College',
  'Edward Waters University',
  'Elizabeth City State University',
  'Elmhurst University',
  'Elon University',
  'Emmanuel University',
  'Erskine College',
  'Fairfield University',
  'Fairleigh Dickinson University',
  'Fayetteville State University',
  'Felician University',
  'Ferris State University',
  'Florida Agricultural and Mechanical University',
  'Florida Atlantic University',
  'Florida Gulf Coast University',
  'Florida International University',
  'Florida Southern College',
  'Florida State University (FSU)',
  'Fordham University',
  'Fort Valley State University',
  'Francis Marion University',
  'Franklin & Marshall College',
  'Franklin Pierce University',
  'Fresno Pacific University',
  'Furman University',
  'Gannon University',
  'Gardner–Webb University',
  'George Mason University',
  'Georgetown University',
  'Georgia Institute of Technology',
  'Georgia Southern University',
  'Georgia State University',
  'Gettysburg College',
  'Gonzaga University',
  'Grambling State University',
  'Grand Canyon University',
  'Grove City College',
  'Gustavus Adolphus College',
  'Hamline University',
  'Hampton University',
  'Hardin–Simmons University',
  'Harvard University',
  'Harvey Mudd College',
  'Haverford College',
  'High Point University',
  'Hilbert College',
  'Hobart and William Smith Colleges',
  'Hofstra University',
  'Houston Christian University',
  'Howard University',
  'Hunter College',
  'Huntingdon College',
  'Idaho State University',
  'Illinois State University',
  'Illinois Wesleyan University',
  'Indiana State University',
  'Indiana University Bloomington',
  'Indiana University–Purdue University Indianapolis',
  'Iona University',
  'Iowa State University of Science and Technology',
  'Ithaca College',
  'Jackson State University',
  'Jacksonville State University',
  'Jacksonville University',
  'James Madison University',
  'John Jay College of Criminal Justice',
  'Johns Hopkins University',
  'Johnson C. Smith University',
  'Kansas State University (KSU)',
  'Kennesaw State University',
  'Kent State University',
  'Kentucky State University',
  'Kentucky Wesleyan College',
  'King University',
  'Kutztown University of Pennsylvania',
  'La Salle University',
  'Lafayette College',
  'Lake Superior State University',
  'Lakeland University',
  'Lamar University',
  'Lawrence University',
  'Le Moyne College',
  'Lees–McRae College',
  'Lehigh University',
  'Leland Stanford Junior University',
  'Lewis University',
  'Liberty University',
  'Limestone University',
  'Lincoln Memorial University',
  'Lindenwood University',
  'Lipscomb University',
  'Livingstone College',
  'Lock Haven University of Pennsylvania',
  'Long Island University Brooklyn',
  'Long Island University',
  'Longwood University',
  'Louisiana State University (LSU)',
  'Louisiana Tech University',
  'Loyola Marymount University',
  'Loyola University Chicago',
  'Loyola University Maryland',
  'Loyola University New Orleans',
  'Macalester College',
  'Manhattan College',
  'Marian University',
  'Marist College',
  'Marquette University',
  'Marshall University',
  'Maryville University of Saint Louis',
  'Massachusetts Institute of Technology',
  'Massachusetts Maritime Academy',
  'McKendree University',
  'McNeese State University',
  'Medaille College',
  'Menlo College',
  'Mercer University',
  'Mercyhurst University',
  'Merrimack College',
  'Miami University',
  'Michigan State University (MSU)',
  'Michigan Technological University',
  'Middle Tennessee State University',
  'Middlebury College',
  'Minnesota State University, Mankato',
  'Mississippi State University for Agriculture and Applied Science',
  'Mississippi Valley State University',
  'Missouri State University',
  'Missouri University of Science and Technology',
  'Molloy University',
  'Monmouth University',
  'Montana State University',
  'Morehead State University',
  'Morehouse College',
  'Morgan State University',
  'Morris Brown College',
  'Mount Aloysius College',
  'Mount Saint Mary’s University',
  'Muhlenberg College',
  'Murray State University',
  'New Jersey City University',
  'New Jersey Institute of Technology',
  'New Mexico State University (NMSU)',
  'New York University (NYU)',
  'Niagara University',
  'Nicholls State University',
  'Norfolk State University',
  'North Carolina Agricultural and Technical State University',
  'North Carolina Central University',
  'North Carolina State University',
  'North Central College',
  'North Dakota State University of Agriculture and Applied Sciences',
  'North Greenville University',
  'Northeastern Illinois University',
  'Northeastern University',
  'Northern Arizona University',
  'Northern Illinois University',
  'Northern Kentucky University',
  'Northern Michigan University',
  'Northwestern State University of Louisiana',
  'Northwestern University',
  'Oakland University',
  'Occidental College',
  'Oklahoma Christian University',
  'Oklahoma City University',
  'Oklahoma State University–Stillwater',
  'Old Dominion University',
  'Oral Roberts University',
  'Oregon State University',
  'Palm Beach Atlantic University',
  'Pennsylvania State University Altoona',
  'Pennsylvania State University Erie, The Behrend College',
  'Pennsylvania Western University Clarion',
  'Pennsylvania Western University Edinboro',
  'Pepperdine University',
  'Pitzer College',
  'Plymouth State University',
  'Pomona College',
  'Portland State University',
  'Post University',
  'Prairie View A&M University',
  'Presbyterian College',
  'Princeton University',
  'Principia College',
  'Providence College',
  'Purdue University Fort Wayne',
  'Purdue University',
  'Queens College, City University of New York',
  'Queens University of Charlotte',
  'Quincy University',
  'Quinnipiac University',
  'Radford University',
  'Regis University',
  'Rensselaer Polytechnic Institute',
  'Rhode Island College',
  'Rider University',
  'Robert Morris University',
  'Roberts Wesleyan University',
  'Rochester Institute of Technology',
  'Rockhurst University',
  'Rose–Hulman Institute of Technology',
  'Rutgers University–New Brunswick',
  'Sacred Heart University',
  'Saint Anselm College',
  'Saint Augustine’s University',
  'Saint Bonaventure University',
  'Saint Cloud State University',
  'Saint Francis College',
  'Saint Francis University',
  'Saint John’s University',
  'Saint Joseph’s University',
  'Saint Lawrence University',
  'Saint Leo University',
  'Saint Louis University',
  'Saint Mary’s College of California',
  'Saint Michael’s College',
  'Saint Olaf College',
  'Saint Peter’s University',
  'Saint Thomas Aquinas College',
  'Saint Vincent College',
  'Salem University',
  'Sam Houston State University',
  'Samford University',
  'San Diego State University (SDSU)',
  'San Jose State University',
  'Santa Clara University',
  'Savannah State University',
  'Scripps College',
  'Seattle University',
  'Seton Hall University',
  'Shaw University',
  'Siena College',
  'Simpson College',
  'Smith College',
  'South Carolina State University',
  'South Dakota State University',
  'Southeast Missouri State University',
  'Southeastern Louisiana University',
  'Southern Connecticut State University',
  'Southern Illinois University Carbondale',
  'Southern Illinois University Edwardsville',
  'Southern Methodist University',
  'Southern New Hampshire University',
  'Southern University and A&M College',
  'Southern Utah University',
  'Spring Hill College',
  'Springfield College',
  'Stanford University',
  'State University of New York at Albany',
  'State University of New York at Binghamton',
  'State University of New York at Buffalo',
  'State University of New York at Stony Brook',
  'State University of New York College at Brockport',
  'State University of New York College at Cortland',
  'State University of New York Maritime College',
  'Stephen F. Austin State University',
  'Stetson University',
  'Stevens Institute of Technology',
  'Stevenson University',
  'Stonehill College',
  'Syracuse University',
  'Tarleton State University',
  'Temple University',
  'Tennessee State University',
  'Tennessee Technological University',
  'Texas A&M University–Commerce',
  'Texas A&M University–Corpus Christi',
  'Texas A&M University–Kingsville',
  'Texas A&M University',
  'Texas Christian University',
  'Texas Southern University',
  'Texas State University',
  'Texas Tech University',
  'The Citadel, The Military College of South Carolina',
  'The College of Saint Scholastica',
  'The College of William and Mary in Virginia',
  'The George Washington University',
  'The Ohio State University',
  'The Ohio University',
  'The Pennsylvania State University (Penn State)',
  'Thomas More University',
  'Towson University',
  'Trinity University',
  'Troy University',
  'Tufts University',
  'Tulane University of Louisiana',
  'Tusculum University',
  'Union College',
  'United States Air Force Academy',
  'United States Coast Guard Academy',
  'United States International University',
  'United States Military Academy',
  'United States Naval Academy',
  'University of Akron',
  'University of Alabama at Birmingham',
  'University of Alabama',
  'University of Alaska Anchorage',
  'University of Alaska Fairbanks',
  'University of Arizona',
  'University of Arkansas',
  'University of Arkansas at Little Rock (UALR)',
  'University of Baltimore',
  'University of Bridgeport',
  'University of California, Berkeley (Cal)',
  'University of California, Davis',
  'University of California, Irvine',
  'University of California, Los Angeles',
  'University of California, Merced',
  'University of California, Riverside',
  'University of California, San Diego',
  'University of California, Santa Barbara',
  'University of Central Arkansas',
  'University of Central Florida (UCF)',
  'University of Central Missouri',
  'University of Charleston',
  'University of Cincinnati',
  'University of Colorado Boulder',
  'University of Connecticut (UConn)',
  'University of Dayton',
  'University of Delaware',
  'University of Denver',
  'University of Detroit Mercy',
  'University of Evansville',
  'University of Florida',
  'University of Georgia',
  'University of Hartford',
  'University of Hawaiʻi at Mānoa',
  'University of Houston',
  'University of Idaho',
  'University of Illinois Chicago',
  'University of Illinois Urbana-Champaign (UIUC)',
  'University of Iowa (UIowa)',
  'University of Jamestown',
  'University of Kansas (KU)',
  'University of Kentucky (UK)',
  'University of La Verne',
  'University of Louisiana at Lafayette',
  'University of Louisiana at Monroe',
  'University of Louisville',
  'University of Maine at Presque Isle',
  'University of Maine',
  'University of Maryland',
  'University of Massachusetts Amherst (UMass)',
  'University of Massachusetts Lowell',
  'University of Memphis',
  'University of Miami',
  'University of Michigan',
  'University of Minnesota Duluth',
  'University of Minnesota',
  'University of Mississippi',
  'University of Missouri–Columbia (Mizzou)',
  'University of Missouri–Kansas City (UMKC)',
  'University of Montana',
  'University of Mount Olive',
  'University of Nebraska Omaha',
  'University of Nebraska–Lincoln (UNL)',
  'University of Nevada, Las Vegas (UNLV)',
  'University of Nevada, Reno',
  'University of New Hampshire',
  'University of New Mexico',
  'University of New Orleans',
  'University of North Alabama',
  'University of North Carolina at Chapel Hill (UNC)',
  'University of North Dakota',
  'University of North Florida',
  'University of North Georgia',
  'University of North Texas',
  'University of Northern Colorado',
  'University of Northern Iowa',
  'University of Notre Dame du Lac',
  'University of Oklahoma (OU)',
  'University of Oregon (UO)',
  'University of Pennsylvania (Penn)',
  'University of Pittsburgh (Pitt)',
  'University of Pittsburgh at Bradford',
  'University of Portland',
  'University of Redlands',
  'University of Rhode Island',
  'University of Richmond',
  'University of Saint Thomas',
  'University of San Diego',
  'University of San Francisco',
  'University of South Alabama',
  'University of South Carolina Upstate',
  'University of South Carolina',
  'University of South Dakota',
  'University of South Florida',
  'University of Southern California (USC)',
  'University of Southern Indiana',
  'University of Southern Mississippi',
  'University of Tampa',
  'University of Tennessee at Chattanooga',
  'University of Tennessee at Martin',
  'University of Tennessee, Knoxville (UTK)',
  'University of Texas at Arlington',
  'University of Texas at Austin (UT)',
  'University of Texas at El Paso (UTEP)',
  'University of Texas at San Antonio',
  'University of Texas Rio Grande Valley',
  'University of Texas–Pan American',
  'University of the Incarnate Word',
  'University of the Pacific',
  'University of Toledo',
  'University of Tulsa',
  'University of Utah',
  'University of Vermont and State Agricultural College',
  'University of Virginia',
  'University of Washington (UW)',
  'University of West Georgia',
  'University of Wisconsin–Eau Claire',
  'University of Wisconsin–Green Bay',
  'University of Wisconsin–La Crosse',
  'University of Wisconsin–Madison (UW)',
  'University of Wisconsin–Milwaukee',
  'University of Wisconsin–Oshkosh',
  'University of Wisconsin–Stout',
  'University of Wisconsin–Whitewater',
  'University of Wyoming',
  'Upper Iowa University',
  'Ursinus College',
  'Ursuline College',
  'Utah State University',
  'Utah Tech University',
  'Utah Valley University',
  'Utica University',
  'Valparaiso University',
  'Vanderbilt University',
  'Vanguard University',
  'Vassar College',
  'Vermont State University',
  'Villanova University',
  'Virginia Commonwealth University',
  'Virginia Military Institute',
  'Virginia Polytechnic Institute and State University',
  'Virginia State University',
  'Virginia Union University',
  'Wagner College',
  'Wake Forest University',
  'Walsh University',
  'Washington & Jefferson College',
  'Washington and Lee University',
  'Washington State University (WSU)',
  'Washington University in St. Louis',
  'Wayne State College',
  'Wayne State University',
  'Weber State University',
  'Wellesley College',
  'West Chester University of Pennsylvania',
  'West Chester University',
  'West Texas A&M University',
  'West Virginia University',
  'Western Carolina University',
  'Western Illinois University',
  'Western Kentucky University',
  'Western Michigan University',
  'Westminster University',
  'Whittier College',
  'Wichita State University (WSU)',
  'William Marsh Rice University',
  'Williams College',
  'Wilmington University',
  'Wilson College',
  'Winona State University',
  'Winthrop University',
  'Wittenberg University',
  'Wofford College',
  'Wright State University',
  'Xavier University',
  'Yale University',
  'Yeshiva University',
  'Youngstown State University',
  "D'Youville University",
]

const G_LEAGUE_TEAMS = [
  'Austin Spurs',
  'Birmingham Squadron',
  'Capital City Go-Go',
  'Capitanes de Ciudad de México',
  'Cleveland Charge',
  'College Park Skyhawks',
  'Delaware Blue Coats',
  'G League Ignite',
  'Grand Rapids Gold',
  'Greensboro Swarm',
  'Indiana Mad Ants',
  'Iowa Wolves',
  'Long Island Nets',
  'Maine Celtics',
  'Memphis Hustle',
  'Motor City Cruise',
  'Oklahoma City Blue',
  'Ontario Clippers',
  'Osceola Magic',
  'Overtime Elite (OTE)',
  'Raptors 905',
  'Rio Grande Valley Vipers',
  'Rip City Remix',
  'Salt Lake City Stars',
  'Santa Cruz Warriors',
  'Sioux Falls Skyforce',
  'South Bay Lakers',
  'Stockton Kings',
  'Texas Legends',
  'Westchester Knicks',
  'Windy City Bulls',
  'Wisconsin Herd',
]

const COUNTRIES = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Democratic Republic of the Congo',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'East Timor',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Ivory Coast',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
]

const NBA_TEAMS = [
  {
    conference: Conference.Eastern,
    division: Division.Atlantic,
    team: 'Boston Celtics',
    location: 'Boston',
    abbreviation: 'BOS',
  },
  {
    conference: Conference.Eastern,
    division: Division.Atlantic,
    team: 'Brooklyn Nets',
    location: 'Brooklyn',
    abbreviation: 'BKN',
  },
  {
    conference: Conference.Eastern,
    division: Division.Atlantic,
    team: 'New York Knicks',
    location: 'New York',
    abbreviation: 'NYK',
  },
  {
    conference: Conference.Eastern,
    division: Division.Atlantic,
    team: 'Philadelphia 76ers',
    location: 'Philadelphia',
    abbreviation: 'PHI',
  },
  {
    conference: Conference.Eastern,
    division: Division.Atlantic,
    team: 'Toronto Raptors',
    location: 'Toronto',
    abbreviation: 'TOR',
  },
  {
    conference: Conference.Eastern,
    division: Division.Central,
    team: 'Chicago Bulls',
    location: 'Chicago',
    abbreviation: 'CHI',
  },
  {
    conference: Conference.Eastern,
    division: Division.Central,
    team: 'Cleveland Cavaliers',
    location: 'Cleveland',
    abbreviation: 'CLE',
  },
  {
    conference: Conference.Eastern,
    division: Division.Central,
    team: 'Detroit Pistons',
    location: 'Detroit',
    abbreviation: 'DET',
  },
  {
    conference: Conference.Eastern,
    division: Division.Central,
    team: 'Indiana Pacers',
    location: 'Indianapolis',
    abbreviation: 'IND',
  },
  {
    conference: Conference.Eastern,
    division: Division.Central,
    team: 'Milwaukee Bucks',
    location: 'Milwaukee',
    abbreviation: 'MIL',
  },
  {
    conference: Conference.Eastern,
    division: Division.Southeast,
    team: 'Atlanta Hawks',
    location: 'Atlanta',
    abbreviation: 'ATL',
  },
  {
    conference: Conference.Eastern,
    division: Division.Southeast,
    team: 'Charlotte Hornets',
    location: 'Charlotte',
    abbreviation: 'CHA',
  },
  {
    conference: Conference.Eastern,
    division: Division.Southeast,
    team: 'Miami Heat',
    location: 'Miami',
    abbreviation: 'MIA',
  },
  {
    conference: Conference.Eastern,
    division: Division.Southeast,
    team: 'Orlando Magic',
    location: 'Orlando',
    abbreviation: 'ORL',
  },
  {
    conference: Conference.Eastern,
    division: Division.Southeast,
    team: 'Washington Wizards',
    location: 'Washington',
    abbreviation: 'WAS',
  },
  {
    conference: Conference.Western,
    division: Division.Northwest,
    team: 'Denver Nuggets',
    location: 'Denver',
    abbreviation: 'DEN',
  },
  {
    conference: Conference.Western,
    division: Division.Northwest,
    team: 'Minnesota Timberwolves',
    location: 'Minneapolis',
    abbreviation: 'MIN',
  },
  {
    conference: Conference.Western,
    division: Division.Northwest,
    team: 'Oklahoma City Thunder',
    location: 'Oklahoma City',
    abbreviation: 'OKC',
  },
  {
    conference: Conference.Western,
    division: Division.Northwest,
    team: 'Portland Trail Blazers',
    location: 'Portland',
    abbreviation: 'POR',
  },
  {
    conference: Conference.Western,
    division: Division.Northwest,
    team: 'Utah Jazz',
    location: 'Salt Lake City',
    abbreviation: 'UTA',
  },
  {
    conference: Conference.Western,
    division: Division.Pacific,
    team: 'Golden State Warriors',
    location: 'San Francisco',
    abbreviation: 'GSW',
  },
  {
    conference: Conference.Western,
    division: Division.Pacific,
    team: 'Los Angeles Clippers',
    location: 'Los Angeles',
    abbreviation: 'LAC',
  },
  {
    conference: Conference.Western,
    division: Division.Pacific,
    team: 'Los Angeles Lakers',
    location: 'Los Angeles',
    abbreviation: 'LAL',
  },
  {
    conference: Conference.Western,
    division: Division.Pacific,
    team: 'Phoenix Suns',
    location: 'Phoenix',
    abbreviation: 'PHX',
  },
  {
    conference: Conference.Western,
    division: Division.Pacific,
    team: 'Sacramento Kings',
    location: 'Sacramento',
    abbreviation: 'SAC',
  },
  {
    conference: Conference.Western,
    division: Division.Southwest,
    team: 'Dallas Mavericks',
    location: 'Dallas',
    abbreviation: 'DAL',
  },
  {
    conference: Conference.Western,
    division: Division.Southwest,
    team: 'Houston Rockets',
    location: 'Houston',
    abbreviation: 'HOU',
  },
  {
    conference: Conference.Western,
    division: Division.Southwest,
    team: 'Memphis Grizzlies',
    location: 'Memphis',
    abbreviation: 'MEM',
  },
  {
    conference: Conference.Western,
    division: Division.Southwest,
    team: 'New Orleans Pelicans',
    location: 'New Orleans',
    abbreviation: 'NOP',
  },
  {
    conference: Conference.Western,
    division: Division.Southwest,
    team: 'San Antonio Spurs',
    location: 'San Antonio',
    abbreviation: 'SAS',
  },
]

const G_LEAGUE_DATA = G_LEAGUE_TEAMS.map((teamName: string) => ({
  name: teamName,
  type: OriginType.G_LEAGUE,
}))

const NCAA_DIV_1_DATA = NCAA_DIV_1_SCHOOLS.map((schoolName: string) => ({
  name: schoolName,
  type: OriginType.UNIVERSITY,
}))

const COUNTRY_DATA = COUNTRIES.map((countryName: string) => ({
  name: countryName,
  type: OriginType.COUNTRY,
}))

const ALL_DATA = [...G_LEAGUE_DATA, ...NCAA_DIV_1_DATA, ...COUNTRY_DATA]

// Function to export autocomplete values to CSV
function exportAutoCompleteToCSV(outputFilename = 'autocomplete-values.csv') {
  // Create CSV header
  const csvHeader = 'name,type\n'

  // Convert autocomplete values to CSV rows
  const csvRows = ALL_DATA.map(
    (item: { name: string; type: OriginType }) =>
      `"${item.name.replace(/"/g, '""')}","${item.type}"`,
  ).join('\n')

  // Combine header and rows
  const csvContent = csvHeader + csvRows

  // Define output directory and file path
  const outputDir = path.join(process.cwd(), 'exports')
  const outputPath = path.join(outputDir, outputFilename)

  // Create directory if it doesn't exist
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true })
  }

  // Write to file
  fs.writeFileSync(outputPath, csvContent, 'utf8')

  console.log(`CSV file successfully created at: ${outputPath}`)
  return outputPath
}

// Get command line arguments
const args = process.argv.slice(2)
const outputFilename = args[0] || 'autocomplete-values.csv'

// Execute the function if this script is run directly
if (require.main === module) {
  exportAutoCompleteToCSV(outputFilename)
}

// Export the function for potential reuse
module.exports = { exportAutoCompleteToCSV }
